name: Process Results
on:
  push:
    paths-ignore:
      - '.github/**'
      - '.gitignore'
      - 'LICENSE'
      - 'README*'
      - 'docs/**'
    branches: [main]

jobs:
  process:
    name: gatling-report
    runs-on: ubuntu-18.04
    # if: github.repository_owner == 'Apicurio'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: AdoptOpenJDK/install-jdk@v1
        with:
          version: '11'
          architecture: x64

      - name: Generate report
        run: ./scripts/run-gatling-report.sh

      - name: Generate web page
        run: ./scripts/generate-web.sh
      
      - name: Commit report
        run: |
          git config --global user.name "apicurio-ci"
          git config --global user.email "apicurio.ci@gmail.com"
          git add reports
          git add index.html
          git commit -m "Automated test results report update"
          git push
